---
argument_specs:
  main:
    short_description: "Install uv, pipx and python (versions) on Linux distributions"
    description: "Install uv, pipx and python (versions) on Linux distributions"
    options:
      python_versions:
        type: "list"
        description: "The extra python versions to install (system is used by default when available)"
        elements: "str"
        default: []
