---
dependencies:
  - role: "uwsm"
  - role: "greetd"
  - role: "nautilus"
  - role: "mako"
  - role: "pipewire"
  - role: "brightnessctl"
  - role: "ddcutil"
  - role: "font"
  - role: "aur_font"
  - role: "waybar"
  - role: "clipse"
  - role: "tofi"
  - role: "hyprcursor"
  - role: "hyprtheme"
galaxy_info:
  author: "a14m"
  description: "Install hyprland"
  license: "MIT"
  min_ansible_version: "2.18"
  platforms:
    - name: "ArchLinux"
      versions:
        - "all"
