---
argument_specs:
  main:
    short_description: "Install hyprland themes on ArchLinux"
    description: "Install hyprland themes on ArchLinux"
    options:
      hyprtheme_default_theme:
        description: "The initial default theme to be used"
        type: "str"
        default: "everforest"
      hyprtheme_default_font:
        description: "The default theme font to be used"
        type: "str"
        default: "JetBrainsMono Nerd Font"
