---
argument_specs:
  main:
    short_description: "Install hyprland themes on ArchLinux"
    description: "Install hyprland themes on ArchLinux"
    options:
      hyprtheme_default_theme:
        description: "The initial default theme to be used"
        type: "str"
        default: "everforest"
      hyprtheme_default_mono_font:
        description: "The default theme mono font to be used"
        type: "str"
        default: "JetBrainsMono Nerd Font"
      hyprtheme_themes_to_install:
        description: "Themes to install"
        type: "list"
        default:
          - "catppuccin"
          - "everforest"
          - "gruvbox"
          - "matte-black"
          - "osaka-jade"
          - "ristretto"
          - "tokyo-night"
