---
argument_specs:
  main:
    short_description: "Install and configure vim"
    description: "Install and configure vim"
    options:
      vimrc_repo_url:
        type: "str"
        description: "The vimrc git repo URL"
        required: true
      vimrc_setup_script:
        type: "str"
        description: "The vimrc setup script"
        required: true
