---
dependencies:
  - role: "xdg-utils"
  - role: "flatpak"
    when: ansible_facts['os_family'] == "Debian"
galaxy_info:
  author: "a14m"
  description: "Configure firefox settings and policies."
  license: "MIT"
  min_ansible_version: "2.18"
  platforms:
    - name: "ArchLinux"
      versions:
        - "all"
    - name: "Ubuntu"
      versions:
        - "noble"
    - name: "Debian"
      versions:
        - "bookworm"
