---
font_packages:
  - "fonts-jetbrains-mono"
  - "fonts-recommended"
  - "fonts-paratype"
  - "fonts-noto"
  - "fonts-noto-cjk"
  - "fonts-noto-color-emoji"
  - "fonts-noto-extra"

font_presets:
  - src: "/usr/share/fontconfig/conf.avail/10-sub-pixel-rgb.conf"
    dest: "/etc/fonts/conf.d/10-sub-pixel-rgb.conf"
  - src: "/usr/share/fontconfig/conf.avail/10-hinting-slight.conf"
    dest: "/etc/fonts/conf.d/10-hinting-slight.conf"
  - src: "/usr/share/fontconfig/conf.avail/11-lcdfilter-default.conf"
    dest: "/etc/fonts/conf.d/11-lcdfilter-default.conf"
