---
- name: "Include OS-specific tasks"
  ansible.builtin.include_tasks: "install-{{ ansible_facts['os_family'] | lower }}.yml"

- name: "Configure xdg-mime defaults"
  ansible.builtin.command:
    cmd: "xdg-mime default org.gnome.Evince.desktop application/pdf"
  changed_when: false
