---
- name: "Ensure gnome-evince is installed"
  become: true
  ansible.builtin.package:
    name: "loupe"
    state: "present"

- name: "Configure xdg-mime defaults"
  ansible.builtin.command:
    cmd: "xdg-mime default org.gnome.Evince.desktop application/pdf"
  changed_when: false
