---
nvidia_packages:
  - "libva-nvidia-driver"

nvidia_aur_packages:
  - "nvidia-580xx-dkms"
  - "nvidia-580xx-utils"
  - "nvidia-580xx-settings"

nvidia_modules:
  - "nvidia"
  - "nvidia_modeset"
  - "nvidia_uvm"
  - "nvidia_drm"
