---
argument_specs:
  main:
    short_description: "Install gpg and pinentry packages"
    description: "Install gpg and pinentry packages"
    options:
      gpg_public_keys:
        type: "list"
        elements: "str"
        required: false
        description: "List of GPG public keys (ASCII armored) to import"
