---
- name: "Reload rules"
  become: true
  ansible.builtin.command:
    cmd: "udevadm control --reload-rules"
  changed_when: true

- name: "Require reboot"
  ansible.builtin.set_fact:
    # This flag is used to trigger a post_task of rebooting after the playbook finishes
    reboot_required: true
