---
gnome_packages:
  - "ubuntu-gnome-desktop"
  - "gdm3"
  - "firefox"
  - "libreoffice-calc"
  - "libreoffice-writer"
  - "libreoffice-impress"
  - "libreoffice-gnome"
  - "rhythmbox"
  - "totem"
  - "cheese"
  - "file-roller"
  - "gnome-calculator"
  - "gnome-calendar"
  - "gnome-characters"
  - "simple-scan"
  - "baobab"
  - "orca"
