---
dependencies: []
galaxy_info:
  author: "a14m"
  description: "Enable multiverse repo"
  license: "MIT"
  min_ansible_version: "2.18"
  platforms:
    - name: "Ubuntu"
      versions:
        - "noble"
