---
- name: "Ensure flatpak is installed"
  become: true
  ansible.builtin.package:
    name: "flatpak"
    state: "present"

- name: "Add flathub remote"
  community.general.flatpak_remote:
    name: "flathub"
    state: "present"
    flatpakrepo_url: "https://dl.flathub.org/repo/flathub.flatpakrepo"
    method: "user"
