---
argument_specs:
  main:
    short_description: "Configure pass for unix (password store)"
    description: "Configure pass for unix (password store)"
    options:
      password_store_repo_url:
        type: "str"
        description: "The password store git repo URL"
        required: true
