---
dependencies:
  - role: "multilib"
    when: ansible_facts['distribution'] == "Archlinux"
  - role: "multiverse"
    when: ansible_facts['distribution'] == "Ubuntu"
galaxy_info:
  author: "a14m"
  description: "Install steam"
  license: "MIT"
  min_ansible_version: "2.18"
  platforms:
    - name: "ArchLinux"
      versions:
        - "all"
    - name: "Ubuntu"
      versions:
        - "noble"
