---
dependencies:
  - role: systemd
galaxy_info:
  author: "a14m"
  description: "Configure distro ssh with hardening"
  license: "license MIT"
  min_ansible_version: "2.18"
  platforms:
    - name: "ArchLinux"
      versions:
        - "all"
    - name: "Ubuntu"
      versions:
        - "noble"
