---
- name: "Include OS-specific variables"
  ansible.builtin.include_vars: "{{ ansible_facts['distribution'] | lower }}.yml"

- name: "Include OS-specific tasks"
  ansible.builtin.include_tasks: "install-{{ ansible_facts['os_family'] | lower }}.yml"

- name: "Configure gnome font"
  ansible.builtin.command:
    cmd: 'gsettings set org.gnome.desktop.interface font-name "Noto Sans"'
  changed_when: false

- name: "Configure gnome perferred color-scheme"
  ansible.builtin.command:
    cmd: 'gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"'
  changed_when: false
