---
- name: "Ensure syshud is installed"
  become: true
  become_user: "aur_builder"
  kewlfft.aur.aur:
    name: "syshud"
    state: "present"
    use: "yay"

- name: "Configure system defaults"
  become: true
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0644"
  loop:
    - src: "config.conf.j2"
      dest: "/usr/share/sys64/hud/config.conf"
    - src: "style.css.j2"
      dest: "/usr/share/sys64/hud/style.css"
