---
- name: "Include OS-specific variables"
  ansible.builtin.include_vars: "{{ ansible_facts['os_family'] | lower }}.yml"

- name: "Ensure the silver searcher (ag) is installed"
  become: true
  ansible.builtin.package:
    name: "{{ ag_package }}"
    state: "present"
