---
dependencies:
  - role: "bash"
  - role: "systemd"
  - role: "sed"
galaxy_info:
  author: "a14m"
  description: "Install and configure WireGuard VPN connections"
  license: "MIT"
  min_ansible_version: "2.18"
  platforms:
    - name: "ArchLinux"
      versions:
        - "all"
    - name: "Ubuntu"
      versions:
        - "noble"
    - name: "Debian"
      versions:
        - "bookworm"
