---
- name: "Restart pihole"
  become: true
  ansible.builtin.systemd_service:
    name: "pihole-FTL"
    state: "restarted"

- name: "Restart systemd-resolved"
  become: true
  ansible.builtin.systemd_service:
    name: "systemd-resolved"
    state: "restarted"

- name: "Restart NetworkManager"
  become: true
  ansible.builtin.systemd_service:
    name: "NetworkManager"
    state: "restarted"
