---
argument_specs:
  main:
    short_description: "Install ansible and molecule on Linux distributions"
    description: "Install ansible and molecule on Linux distributions"
    options:
      ansible_core_version:
        type: "str"
        description: "The default ansible-core version to use (must be in major.minor.patch format)"
        default: "2.19.3"
      molecule_version:
        type: "str"
        description: "The default molecule version to use (must be in major.minor.patch format)"
        default: "25.9.0"
      ansible_lint_version:
        type: "str"
        description: "The default ansible-lint version to use (must be in major.minor.patch format)"
        default: "25.9.2"
