---
dependencies:
  - role: "python"
galaxy_info:
  author: "a14m"
  description: "Install ansible and molecule using uv on Linux distributions"
  license: "MIT"
  min_ansible_version: "2.18"
  platforms:
    - name: "ArchLinux"
      versions:
        - "all"
    - name: "Ubuntu"
      versions:
        - "noble"
    - name: "Debian"
      versions:
        - "bookworm"
