---
dependencies:
  - role: "network"
  - role: "systemd"
galaxy_info:
  author: "a14m"
  description: "Configure pihole on supported devices"
  license: "MIT"
  min_ansible_version: "2.18"
  platforms:
    - name: "Ubuntu"
      versions:
        - "noble"
    - name: "Debian"
      versions:
        - "bookworm"
