---
dependencies:
  - role: "yay"
galaxy_info:
  author: "a14m"
  description: "Install wlctl"
  license: "MIT"
  min_ansible_version: "2.18"
  platforms:
    - name: "ArchLinux"
      versions:
        - "all"
