---
dependencies:
  - role: "git"
galaxy_info:
  author: "a14m"
  description: "Install Nautilus file manager on ArchLinux"
  company: "kartoffeln.work GmbH."
  license: "MIT"
  min_ansible_version: "2.18"
  platforms:
    - name: "ArchLinux"
      versions:
        - "all"
