---
- name: "Include OS-specific variables"
  ansible.builtin.include_vars: "{{ ansible_facts['os_family'] | lower }}.yml"

- name: "Ensure password_policy package is installed"
  become: true
  ansible.builtin.package:
    name: "{{ password_policy_package }}"
    state: "present"

- name: "Configure archlinux password policy"
  become: true
  ansible.builtin.template:
    src: "archlinux-pam-pw.j2"
    dest: "/etc/pam.d/system-auth"
    mode: "0644"
  when: ansible_facts['os_family'] == "Archlinux"

- name: "Configure debian password policy"
  become: true
  ansible.builtin.template:
    src: "debian-pam-pw.j2"
    dest: "/etc/pam.d/common-password"
    mode: "0644"
  when: ansible_facts['os_family'] == "Debian"
