---
- name: "Ensure pulseaudio is removed"
  become: true
  ansible.builtin.apt:
    pkg: "pulseaudio"
    state: "absent"
    autoremove: true
    purge: true

- name: "Ensure pipewire packages are installed"
  become: true
  ansible.builtin.apt:
    pkg:
      - "pipewire"
      - "wireplumber"
      - "pipewire-pulse"
      - "pipewire-alsa"
    state: "present"
