---
elephant_packages:
  - "elephant-bin"
  # - "elephant-archlinuxpkgs-bin"
  - "elephant-calc-bin"
  - "elephant-clipboard-bin"
  - "elephant-desktopapplications-bin"
  # - "elephant-files-bin"
  # - "elephant-menus"
  - "elephant-providerlist-bin"
  # - "elephant-runner-bin"
  - "elephant-symbols-bin"
  # - "elephant-todo-bin"
  - "elephant-unicode-bin"
  - "elephant-websearch-bin"
  - "elephant-windows-bin"
