---
dependencies:
  - role: "font"
  - role: "alacritty"
  - role: "btop"
  - role: "bluetui"
  - role: "wlctl"
  - role: "wiremix"
  - role: "gnome-calendar"
galaxy_info:
  author: "a14m"
  description: "Install waybar"
  license: "MIT"
  min_ansible_version: "2.18"
  platforms:
    - name: "ArchLinux"
      versions:
        - "all"
